{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spinyowl",
    "module": "cbchain",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "cbchain-1.0.1.jar",
          "url": "cbchain-1.0.1.jar",
          "size": 26370,
          "sha512": "a4f02b4001ce2cc894f37b4f6748c3c675c9fc9d46029ef366c3855116ecd114d3013e711a2943d6625588127bdaec4f294807ea7e3f6488deddcd3b3e6f5504",
          "sha256": "8616c949d06cb8d9ee1675a57826d4bf4f44d71af3f99f9516a4caffb58ca6e6",
          "sha1": "36175319bba37060bed7f7d4af438715a75e25e5",
          "md5": "681ac518c63659b56ae17402ec1d45dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "cbchain-1.0.1.jar",
          "url": "cbchain-1.0.1.jar",
          "size": 26370,
          "sha512": "a4f02b4001ce2cc894f37b4f6748c3c675c9fc9d46029ef366c3855116ecd114d3013e711a2943d6625588127bdaec4f294807ea7e3f6488deddcd3b3e6f5504",
          "sha256": "8616c949d06cb8d9ee1675a57826d4bf4f44d71af3f99f9516a4caffb58ca6e6",
          "sha1": "36175319bba37060bed7f7d4af438715a75e25e5",
          "md5": "681ac518c63659b56ae17402ec1d45dc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cbchain-1.0.1-javadoc.jar",
          "url": "cbchain-1.0.1-javadoc.jar",
          "size": 516740,
          "sha512": "b8b7eb5de34fffbb13b73b40530eea75bcbccf61f3141fe5157d4cfc4ce5f03ba5a0c35f5c694a084ef814ab32556dcda07e54176f3098506dc957ff858b47c8",
          "sha256": "6fb7b306d4a89b2460e19684977aae21a9c0beda5d1a086f73a8985c7353a1e7",
          "sha1": "3718d5785ba628baba0b5e451bc83534c4f7e9bd",
          "md5": "3000f506778ffc1ece23c0a4208fed41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cbchain-1.0.1-sources.jar",
          "url": "cbchain-1.0.1-sources.jar",
          "size": 18290,
          "sha512": "90fc3dd095a7479a8a00fac3267638ceb4e610a11d528cdfaad4817a6d95c960c1a71f9082c814146026f2aee6fa94986f405b5083ce2a84ec98ef4151b9a9f6",
          "sha256": "2dc4c3adb8b42a60b3c65db11eb2e0c32ad5c3e11255c7d9b5552cbb8260588d",
          "sha1": "413f6ab1717d597675a5aa881ffdd3230f399fce",
          "md5": "e4069041df38091a9cb596c3158c26d0"
        }
      ]
    }
  ]
}
