{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spinyowl",
    "module": "cbchain",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "cbchain-1.0.0.jar",
          "url": "cbchain-1.0.0.jar",
          "size": 26441,
          "sha512": "332708dd2190ebceec3c8f70c1bc3612c910995ac1fa9c21571ca9d012481497e16d719c5e1a3d53cc0a27f629debe4967ae31cde0748642982e41422a491423",
          "sha256": "43484e3308872cbeacedb4f1dc86bae92392a240a606225c8747361746826936",
          "sha1": "4f2e0e8fb2ff49f2caa2e7569d82531c433fb1f3",
          "md5": "fde3ca85c0087e79299485e2c7a56971"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "cbchain-1.0.0.jar",
          "url": "cbchain-1.0.0.jar",
          "size": 26441,
          "sha512": "332708dd2190ebceec3c8f70c1bc3612c910995ac1fa9c21571ca9d012481497e16d719c5e1a3d53cc0a27f629debe4967ae31cde0748642982e41422a491423",
          "sha256": "43484e3308872cbeacedb4f1dc86bae92392a240a606225c8747361746826936",
          "sha1": "4f2e0e8fb2ff49f2caa2e7569d82531c433fb1f3",
          "md5": "fde3ca85c0087e79299485e2c7a56971"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cbchain-1.0.0-javadoc.jar",
          "url": "cbchain-1.0.0-javadoc.jar",
          "size": 221551,
          "sha512": "26d94fa6f01d9374465ae6e8c137ed409c603c4f2a26bb9d6910025066abd7653c11d8c0700445525fd8a8f257f4efe81b0023bde22ae2287d6d2f60831f8160",
          "sha256": "d70f9eb0a29b085620a02951a21493423d79d2cd7fc238ab65395d344f44e3dd",
          "sha1": "e8f23e39c6d64ad2af83032e295d9bc36cf3fa8f",
          "md5": "f8f5fb9d136400cd86b130f0b7545adb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cbchain-1.0.0-sources.jar",
          "url": "cbchain-1.0.0-sources.jar",
          "size": 18290,
          "sha512": "50bada96ba34b59c84bfb1c3fd6fcc40cbc33eacc94856b688269c5cd72ca7dab9561d4d20bebc4fbcea6cf69e3501bec856142a62203466dc906c751aa12bee",
          "sha256": "a773f96b8f5e30506f8be9797c5055b93d4554d3af1822724bdf9b70a980ef1b",
          "sha1": "2455e206f2e1135039e8c88dc91c51f53ec2020d",
          "md5": "a7dfb42696773fcc98056c99a309266c"
        }
      ]
    }
  ]
}
