{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spinyowl",
    "module": "cbchain",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "cbchain-1.0.0.jar",
          "url": "cbchain-1.0.0.jar",
          "size": 26104,
          "sha512": "da7980f5852a2be8b3a29ef65f0b9bae86797b888bba441cbd7e579b98a8ecd17748fe9bc289692ab7ad984d05eb6bd8ec925579a9a02c72e46da76dae36dcbe",
          "sha256": "6b5753067521e8967d964d1b11e5aab6120825edc2b95ede7fdadbfb3672512c",
          "sha1": "71438ab2cc2d95776791f5b766421e9bfc7b7fe5",
          "md5": "abcfd5a589eb384ee6f65223e7ea3aa0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "cbchain-1.0.0.jar",
          "url": "cbchain-1.0.0.jar",
          "size": 26104,
          "sha512": "da7980f5852a2be8b3a29ef65f0b9bae86797b888bba441cbd7e579b98a8ecd17748fe9bc289692ab7ad984d05eb6bd8ec925579a9a02c72e46da76dae36dcbe",
          "sha256": "6b5753067521e8967d964d1b11e5aab6120825edc2b95ede7fdadbfb3672512c",
          "sha1": "71438ab2cc2d95776791f5b766421e9bfc7b7fe5",
          "md5": "abcfd5a589eb384ee6f65223e7ea3aa0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cbchain-1.0.0-javadoc.jar",
          "url": "cbchain-1.0.0-javadoc.jar",
          "size": 217764,
          "sha512": "030983e15ed800b54bd0ad440f8c3ec2882f92c8264ecb602d968d6b03910aee87d0158e5d375ec12e4f74d04d8f22d8f33ca21e71924fd510c50f41aa9613ba",
          "sha256": "b5d3fda584d37008019e962144cedd2f4d4df35ddd5a0a992c42a7693bc80717",
          "sha1": "c6d9caeb26056ec093859c96ae68960f7da97b6f",
          "md5": "2ee1973b6468a33e2728c279deb8b8b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cbchain-1.0.0-sources.jar",
          "url": "cbchain-1.0.0-sources.jar",
          "size": 18083,
          "sha512": "394c71ff8e84c3ec04694d98362dbb4c4c1f708c815d4456eb54852c9dcc205b5d1b0c042a2b89b2a5e646c7cb618072ea08a94030e19921ab8db711778e9649",
          "sha256": "0e8683d786dc7e1adce1cdaf4125e1c9d2f262162c06fc1aa5e0edf2c02b5e3c",
          "sha1": "83452a91aabea831877e0ce05c7d9692f48fafb2",
          "md5": "aaff117fe8a4f13c427adda79fc73cba"
        }
      ]
    }
  ]
}
