{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spinyowl",
    "module": "legui",
    "version": "4.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.38"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-jre"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.spinyowl",
          "module": "cbchain",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "legui-4.2.1.jar",
          "url": "legui-4.2.1.jar",
          "size": 1379959,
          "sha512": "6d2a25b41ce2c2b6b577b1a0fe4e77aab4f9db5e0ca63cea96af53cc6ce3466fa796ebb2067d76eb1b2c4805dac08d7408613357c168713ddb4acea69ce456cc",
          "sha256": "74e5cd29d844bd7589a8c8dc5e08f24250567aa4101ebc75e5326367fc3affb7",
          "sha1": "9747f6cf672644b6fe22b1012293ebd1d1aa1c61",
          "md5": "c3ccedb9211d9b93c36f0af0ad2116ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.38"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-jre"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.spinyowl",
          "module": "cbchain",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.6"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "legui-4.2.1.jar",
          "url": "legui-4.2.1.jar",
          "size": 1379959,
          "sha512": "6d2a25b41ce2c2b6b577b1a0fe4e77aab4f9db5e0ca63cea96af53cc6ce3466fa796ebb2067d76eb1b2c4805dac08d7408613357c168713ddb4acea69ce456cc",
          "sha256": "74e5cd29d844bd7589a8c8dc5e08f24250567aa4101ebc75e5326367fc3affb7",
          "sha1": "9747f6cf672644b6fe22b1012293ebd1d1aa1c61",
          "md5": "c3ccedb9211d9b93c36f0af0ad2116ea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legui-4.2.1-javadoc.jar",
          "url": "legui-4.2.1-javadoc.jar",
          "size": 5697729,
          "sha512": "2cc26b1d5805cbad901d483c462ca0c548ce19de9a723576e614aa81f2a024fe5868f91b7c9fbfccbf66a7d28c007c7ff3ab7b56f6977a55cefe921c1e554de3",
          "sha256": "701c30849c3cce4c1baa15998d74ce09862c5888fa135268d31dcfbcd0ce19a5",
          "sha1": "40244ae0a9c7130907d315d7fc4ad2c0be09acc2",
          "md5": "0eba03ec5b828742131d2ffebb2f9b3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legui-4.2.1-sources.jar",
          "url": "legui-4.2.1-sources.jar",
          "size": 1320352,
          "sha512": "cbe070dc35047bb417825219c7bdb650f9d79f5af34723a1f7c64e1ec8f8c71251fec5c5f4e43d137d79356f7be0f0a5aca4050b7c5de3b1bd2bdb0337cead13",
          "sha256": "ea2ef6f73b9d7bd910f26e9e267af7566e06ce82fdd112b733399387bde864e0",
          "sha1": "a1849acab35e747491b8fbfff4f6f1c740b64156",
          "md5": "8150f7daced04f52cbe87e14b1f05894"
        }
      ]
    }
  ]
}
