{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spinyowl",
    "module": "legui",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.spinyowl",
          "module": "cbchain",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "legui-4.1.0.jar",
          "url": "legui-4.1.0.jar",
          "size": 1365597,
          "sha512": "6aed325658603b08934bc9910e2f8febd3a9f09b738512846e6d4d83f84879a1b0c1cc2a7d684e41b44a88a47c30b3f3bbe9873e486b53bce66008a200cc2188",
          "sha256": "4733764358609ce001e935532bc162266f251734b4b6c19d2ccfa5d473c1ad03",
          "sha1": "41ee101907512639977cbd0d39138fb21446ce78",
          "md5": "0d6b8edbda7ca6f80245f5e1a5f99740"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.spinyowl",
          "module": "cbchain",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-yoga",
          "version": {
            "requires": "3.3.1-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-yoga",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "legui-4.1.0.jar",
          "url": "legui-4.1.0.jar",
          "size": 1365597,
          "sha512": "6aed325658603b08934bc9910e2f8febd3a9f09b738512846e6d4d83f84879a1b0c1cc2a7d684e41b44a88a47c30b3f3bbe9873e486b53bce66008a200cc2188",
          "sha256": "4733764358609ce001e935532bc162266f251734b4b6c19d2ccfa5d473c1ad03",
          "sha1": "41ee101907512639977cbd0d39138fb21446ce78",
          "md5": "0d6b8edbda7ca6f80245f5e1a5f99740"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legui-4.1.0-javadoc.jar",
          "url": "legui-4.1.0-javadoc.jar",
          "size": 1931430,
          "sha512": "4d961762d40052811133db4fd4e3836c43054a17343f073f26424b663bc9b5eee325b2f83329e7fdad6ae44b2a05091323a55e3692197b4e53a51c52105f4b1e",
          "sha256": "8044fd42f364cf43eb51bce4c24f93ddff60c5ef168366fcb719baa812a7bc44",
          "sha1": "c60451b58482167965e091ede4760b2eeb1c14c0",
          "md5": "3a2a640a9575aa8028e6ecb2b9974084"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legui-4.1.0-sources.jar",
          "url": "legui-4.1.0-sources.jar",
          "size": 1319426,
          "sha512": "57fda1a5548e3b960e1396c309e89592a7693e17207adeae93be57e774452bc40311569226b856d3bef7c7ca51ddfab3e77dd9eeaa081c6e747728c81f504d37",
          "sha256": "f8512898d0c9b8299528d5cea31f95e11848301324058897104f5e91fefff5ab",
          "sha1": "ceb5e03fd3fdb6200cf23fdc254af7ba039cc96e",
          "md5": "875064b70f5ffac9e79e8142b7a2b5a8"
        }
      ]
    }
  ]
}
