{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spinyowl",
    "module": "cbchain",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "cbchain-1.0.2.jar",
          "url": "cbchain-1.0.2.jar",
          "size": 26373,
          "sha512": "8cf41bf4a3bf4ebff8535b51387b71f82d8f67e5c0c2aaf3b0da09258b3cf780faad0e1ea89bebc93b5478e69e00dccef8c5d450dfb606699493c3ba905c30db",
          "sha256": "7a062a5b3faac394f5708175d83ecd6dee5fb068aa2555ff6a73bc77d59b1eb8",
          "sha1": "4e37a0dd09bb6cc9588559692fba127c86dc81c8",
          "md5": "c2a2a705bfb15a253f8e1f8bbc078b3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        }
      ],
      "files": [
        {
          "name": "cbchain-1.0.2.jar",
          "url": "cbchain-1.0.2.jar",
          "size": 26373,
          "sha512": "8cf41bf4a3bf4ebff8535b51387b71f82d8f67e5c0c2aaf3b0da09258b3cf780faad0e1ea89bebc93b5478e69e00dccef8c5d450dfb606699493c3ba905c30db",
          "sha256": "7a062a5b3faac394f5708175d83ecd6dee5fb068aa2555ff6a73bc77d59b1eb8",
          "sha1": "4e37a0dd09bb6cc9588559692fba127c86dc81c8",
          "md5": "c2a2a705bfb15a253f8e1f8bbc078b3a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cbchain-1.0.2-javadoc.jar",
          "url": "cbchain-1.0.2-javadoc.jar",
          "size": 404592,
          "sha512": "90e6ffc25c9f33e980851f569d82cd87e272d2379d00920963929e10a7f5052710c4acc7207ba2b30db83f4d74a7649eef23b0c7b93d9405291bc75d8b07f12a",
          "sha256": "b5086905140d9574b1b7c1e780f8262d663b76f9b78333ff1acb4d428f90169b",
          "sha1": "9d7d1faaddfc7e3e41f4deaade85c0a00a5387c3",
          "md5": "fba149ec83ec0c16455e16c8689263ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cbchain-1.0.2-sources.jar",
          "url": "cbchain-1.0.2-sources.jar",
          "size": 18290,
          "sha512": "b97f0f2f528f747ad27875882731377f60a4410a4ae066ea41eeb4ad2a082f89ef3880d5ed2067d9a6baf83563da4fda492d33c78e753f33be7597f47854e584",
          "sha256": "f3f2d15ff385d566033cbc118e97fa0181b9dd29e058d93ebc1a5cbf012ab573",
          "sha1": "875f384e781f04fe6e8b83da09fb3362447b6a42",
          "md5": "0bae8084d7b77827d19b28c608d2c2a6"
        }
      ]
    }
  ]
}
